### ISSUE TITLE
Support Ruby 3?

### ISSUE THREAD

**Issue by Shimokuni** [r7kamura/jdoc#14]
@r7kamura same as https://github.com/r7kamura/rack-json_schema/issues/14

https://github.com/r7kamura/jdoc/blob/42fb0d063313bf6b8eae39ddd8bc1e55381d2890/lib/jdoc/generator.rb#L8-L21

If I make a PR to fix this, could you review and merge it?

**Comment by r7kamura** [comment]
Same as https://github.com/r7kamura/rack-json_schema/issues/14#issuecomment-1891274539.

**Comment by Shimokuni** [comment]
@r7kamura Thank you!
I made PR. Could you review and merge it?
https://github.com/r7kamura/jdoc/pull/15
